import { useMemo, useState } from "react";
import { ArrowUpRight, BadgeCheck, Box, Calculator, CheckCircle2, ChevronRight, ClipboardCheck, Cloud, Download, FileSpreadsheet, FileText, Layers3, Menu, PackageCheck, Plus, Save, Send, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import { ThreeDesigner } from "@/components/ThreeDesigner";
import { calculateQuote, defaultCostInputs, type CostInputs } from "@/lib/quote";
import { supabase, supabaseReady } from "@/lib/supabase";
import { saveWorkspaceSnapshot } from "@/lib/workspace";
import { initialDesign, initialParts, type DesignPart, type DesignState, type PlushKind } from "@/lib/studioTypes";

type Tab = "overview" | "design" | "spec" | "quote" | "qa" | "production";
const tabItems: Array<[Tab, string, typeof Box]> = [["overview", "개요", Layers3], ["design", "3D 디자인", Box], ["spec", "제조 사양", ClipboardCheck], ["quote", "견적 시뮬레이션", Calculator], ["qa", "샘플 & QA", BadgeCheck], ["production", "양산 관리", PackageCheck]];
const fmt = new Intl.NumberFormat("ko-KR", { style: "currency", currency: "KRW", maximumFractionDigits: 0 });

function Pill({ children, accent = false }: { children: React.ReactNode; accent?: boolean }) { return <span className={`status-pill ${accent ? "status-accent" : ""}`}>{children}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }

export default function Home() {
  const [tab, setTab] = useState<Tab>("overview"); const [menu, setMenu] = useState(false); const [design, setDesign] = useState<DesignState>(initialDesign); const [parts, setParts] = useState<DesignPart[]>(initialParts); const [cost, setCost] = useState<CostInputs>(defaultCostInputs); const [note, setNote] = useState("변경 내용은 현재 작업 세션에 보관됩니다."); const [login, setLogin] = useState(false); const [email, setEmail] = useState("");
  const quote = useMemo(() => calculateQuote({ ...cost, heightCm: design.heightCm, partCount: parts.length }), [cost, design.heightCm, parts.length]);
  const edit = <K extends keyof DesignState>(key: K, value: DesignState[K]) => { setDesign(value_ => ({ ...value_, [key]: value })); setNote("3D 형태 변경이 현재 버전에 반영되었습니다."); };
  const updateCost = <K extends keyof CostInputs>(key: K, value: CostInputs[K]) => setCost(value_ => ({ ...value_, [key]: value }));
  const exportXlsx = async () => { try { const XLSX = await import("xlsx"); const sheet = XLSX.utils.json_to_sheet(parts.map(item => ({ "부위 ID": item.code, "부위명": item.name, "원단/소재": item.material, "가로(mm)": item.widthMm, "세로(mm)": item.heightMm, "깊이(mm)": item.depthMm, "허용오차(±mm)": item.toleranceMm }))); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, "BOM"); XLSX.writeFile(book, `${design.name}-BOM.xlsx`); setNote("BOM XLSX를 생성했습니다."); } catch { setNote("XLSX 생성에 실패했습니다. 브라우저 다운로드 권한을 확인해 주세요."); } };
  const exportPdf = async () => { try { const { jsPDF } = await import("jspdf"); const pdf = new jsPDF(); pdf.setFontSize(18); pdf.text("PLUSH STUDIO / TECH PACK", 14, 18); pdf.setFontSize(11); pdf.text(`Design: ${design.name} / V1.2`, 14, 30); pdf.text(`Final height: ${design.heightCm} cm | QA: dimensions, fabric, embroidery, seam, packaging`, 14, 38); parts.forEach((item, i) => pdf.text(`${item.code} | ${item.name} | ${item.material} | ${item.widthMm} x ${item.heightMm} x ${item.depthMm} mm | +/- ${item.toleranceMm} mm`, 14, 52 + i * 9)); pdf.save(`${design.name}-tech-pack.pdf`); setNote("Tech Pack PDF를 생성했습니다."); } catch { setNote("PDF 생성에 실패했습니다. 브라우저 다운로드 권한을 확인해 주세요."); } };
  const signIn = async () => { if (!supabase || !email.includes("@")) { setNote("Supabase 연결값과 업무 이메일을 확인해 주세요."); return; } const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: window.location.origin } }); setNote(error ? "로그인 링크 발송에 실패했습니다. Auth 설정을 점검해 주세요." : "로그인 링크를 이메일로 보냈습니다."); };
  const saveCloud = async () => { try { const saved = await saveWorkspaceSnapshot(design, parts, cost, quote); setNote(`Supabase에 프로젝트와 V1.0 디자인을 저장했습니다. · ${saved.projectId.slice(0, 8)}`); } catch (error) { setNote(error instanceof Error && error.message === "AUTH_REQUIRED" ? "클라우드 저장은 로그인 후 사용할 수 있습니다." : "저장에 실패했습니다. 조직 권한과 네트워크를 확인해 주세요."); } };
  const updatePart = (id: string, key: keyof DesignPart, value: string | number) => setParts(items => items.map(item => item.id === id ? { ...item, [key]: value } : item));
  const page = () => {
    if (tab === "design") return <section className="design-layout"><article className="panel controls"><header><p className="eyebrow">DESIGN CONTROL</p><h2>기본형을 빠르게 맞추세요.</h2></header><Field label="디자인명"><input value={design.name} onChange={e => edit("name", e.target.value)} /></Field><div className="segmented">{(["bear", "rabbit", "cat"] as PlushKind[]).map(kind => <button type="button" className={design.kind === kind ? "selected" : ""} key={kind} onClick={() => edit("kind", kind)}>{kind === "bear" ? "곰" : kind === "rabbit" ? "토끼" : "고양이"}</button>)}</div><Range label="완성 높이" value={design.heightCm} unit="cm" min={10} max={80} step={1} onChange={v => edit("heightCm", v)} /><Range label="머리 비율" value={design.headScale} unit="x" min={0.7} max={1.4} step={0.01} onChange={v => edit("headScale", v)} /><Range label="몸통 비율" value={design.bodyScale} unit="x" min={0.7} max={1.4} step={0.01} onChange={v => edit("bodyScale", v)} /><Range label="귀 길이" value={design.earScale} unit="x" min={0.65} max={1.8} step={0.01} onChange={v => edit("earScale", v)} /><div className="color-row"><Field label="본체"><input type="color" value={design.color} onChange={e => edit("color", e.target.value)} /></Field><Field label="포인트"><input type="color" value={design.accent} onChange={e => edit("accent", e.target.value)} /></Field></div><label className="check-row"><input type="checkbox" checked={design.keyring} onChange={e => edit("keyring", e.target.checked)} /> 키링 링 포함</label><div className="callout"><Layers3 size={18} /><p><strong>삼면도 · 부위 조립 모드</strong><br />참조 이미지를 업로드하고 윤곽을 지정해 부위 단위로 검토합니다.</p></div></article><article className="model-panel"><ThreeDesigner design={design} view="perspective" /><footer><span><i className="live-dot" /> LIVE 3D · {design.heightCm} cm</span><span>드래그 회전 · 스크롤 확대</span></footer></article></section>;
    if (tab === "spec") return <section className="spec-page"><header className="section-header"><div><p className="eyebrow">TECHNICAL SPECIFICATION</p><h2>부위별 제조 사양과 BOM</h2><p>도안·소재·치수·허용오차를 승인된 버전에 귀속합니다.</p></div><div className="button-row"><button className="quiet-button" onClick={exportXlsx}><FileSpreadsheet size={16} /> XLSX</button><button className="primary-button" onClick={exportPdf}><FileText size={16} /> Tech Pack PDF</button></div></header><article className="panel bom-panel"><header><strong>ACTIVE BOM / V1.2</strong><button className="outline-button" onClick={() => setParts(items => [...items, { id: crypto.randomUUID(), code: `PT-${String(items.length + 1).padStart(2, "0")}`, name: "새 부위", type: "detail", material: "원단 지정", widthMm: 10, heightMm: 10, depthMm: 10, toleranceMm: 2 }])}><Plus size={16} /> 부위 추가</button></header><div className="bom-scroll"><table><thead><tr><th>부위</th><th>소재 · 원단</th><th>가로</th><th>세로</th><th>깊이</th><th>오차</th></tr></thead><tbody>{parts.map(item => <tr key={item.id}><td><b>{item.code}</b><input value={item.name} onChange={e => updatePart(item.id, "name", e.target.value)} /></td><td><input value={item.material} onChange={e => updatePart(item.id, "material", e.target.value)} /></td><td><NumberInput value={item.widthMm} onChange={v => updatePart(item.id, "widthMm", v)} /></td><td><NumberInput value={item.heightMm} onChange={v => updatePart(item.id, "heightMm", v)} /></td><td><NumberInput value={item.depthMm} onChange={v => updatePart(item.id, "depthMm", v)} /></td><td><NumberInput value={item.toleranceMm} onChange={v => updatePart(item.id, "toleranceMm", v)} /></td></tr>)}</tbody></table></div></article><div className="feature-row"><Feature icon={<Box size={20} />} title="봉제 & 공정" text="봉제선, 충전량, 자수 위치를 부위별로 기록" /><Feature icon={<PackageCheck size={20} />} title="포장 & 물류" text="OPP, 행택, 외박스, CBM 및 MOQ를 연결" /><Feature icon={<ShieldCheck size={20} />} title="품질 허용오차" text="사양을 샘플 및 양산 QA 기준으로 이동" /></div></section>;
    if (tab === "quote") return <section className="quote-layout"><article className="panel quote-input"><header><p className="eyebrow">RULE-BASED COST ENGINE</p><h2>변수를 바꾸면 즉시 다시 계산됩니다.</h2></header><div className="input-grid">{([[["quantity", "견적 수량", "pcs"], ["fabricCny", "원단·충전재", "CNY"], ["embroideryCny", "자수·프린트", "CNY"], ["trimsCny", "부자재", "CNY"], ["sewingDifficulty", "봉제 난이도", "배"], ["packagingCny", "포장", "CNY"], ["logisticsCny", "물류·통관", "CNY"], ["exchangeRate", "적용 환율", "KRW"], ["marginRate", "목표 마진", "%"]] as [keyof CostInputs, string, string][]][0]).map(([key, label, unit]) => <Field key={key} label={label}><div className="input-unit"><input type="number" value={key === "marginRate" ? Math.round(cost[key] * 100) : cost[key]} onChange={e => updateCost(key, (key === "marginRate" ? Number(e.target.value) / 100 : Number(e.target.value)) as never)} /><span>{unit}</span></div></Field>)}</div></article><article className="quote-result"><p className="eyebrow">ESTIMATED UNIT ECONOMICS</p><h2>{fmt.format(quote.targetPriceKrw)}</h2><p>권장 소비자가 · 목표 마진 반영</p><dl><div><dt>소재 원가</dt><dd>¥ {quote.materialsCny.toFixed(2)}</dd></div><div><dt>봉제 공임</dt><dd>¥ {quote.laborCny.toFixed(2)}</dd></div><div><dt>예상 착지 원가</dt><dd>{fmt.format(quote.landedCostKrw)}</dd></div><div className="total"><dt>총 제조·착지 원가</dt><dd>{fmt.format(quote.totalCostKrw)}</dd></div></dl><button className="primary-button full"><Send size={16} /> 공장 견적 요청 준비</button><small>실제 공장 견적·샘플·물류 견적과 비교한 후 승인하세요.</small></article></section>;
    if (tab === "qa") return <section className="qa-layout"><article className="panel sample-panel"><header><p className="eyebrow">SAMPLE REVIEW / ROUND 01</p><h2>이미지 기반으로 부위별 수정 요청을 남기세요.</h2></header><div className="sample-placeholder"><Box size={42} /><strong>샘플 사진 업로드 영역</strong><span>정면 · 측면 · 봉제 디테일 · 패키지</span></div><Field label="공장에 전달할 수정 요청"><textarea placeholder="예: PT-03 귀 높이를 3 mm 낮추고 자수 위치를 2 mm 위로 조정해 주세요." /></Field><button className="primary-button"><Send size={16} /> 피드백 등록</button></article><article className="qa-card"><p className="eyebrow">QA CHECKLIST</p><h2>승인 전 필수 확인</h2>{["치수 허용오차", "원단 컬러 및 파일 길이", "자수 위치와 선명도", "봉제선·충전량·대칭", "부자재 견고성", "포장 및 바코드"].map((item, i) => <label key={item}><input type="checkbox" defaultChecked={i < 2} /><span>{item}</span><Pill accent={i < 2}>{i < 2 ? "확인" : "대기"}</Pill></label>)}<button className="outline-button full"><CheckCircle2 size={16} /> 샘플 승인 요청</button></article></section>;
    if (tab === "production") return <section className="production-page"><header className="section-header"><div><p className="eyebrow">PRODUCTION CONTROL</p><h2>승인된 사양을 양산까지 유지하세요.</h2><p>발주·공장 일정·인라인 및 출고 전 검사 결과를 이력으로 연결합니다.</p></div><button className="primary-button"><Plus size={16} /> 발주 생성</button></header><article className="production-card"><div><Pill>PO-2026-014</Pill><h3>1,000 pcs · 공장 확정 전</h3><p>승인된 V1.2, Tech Pack과 최종 견적이 발주서에 고정됩니다.</p></div><Pill accent>준비 중</Pill></article><article className="timeline"><strong>In-line <ChevronRight size={15} /> Pre-shipment <ChevronRight size={15} /> 출고 승인</strong><p>부적합 항목은 QA 결과와 증빙 사진으로 기록하고 해결 전 출고 승인을 잠급니다.</p></article></section>;
    return <section className="overview-layout"><article className="overview-main"><header className="section-header"><div><p className="eyebrow">PROJECT PULSE</p><h2>결정을 위한 단일 작업 화면</h2></div><Pill accent>내부 검토</Pill></header><div className="metric-grid"><Metric icon={<Box />} label="완성 높이" value={`${design.heightCm} cm`} hint="3D 비율 기준" /><Metric icon={<Calculator />} label="목표 소비자가" value={fmt.format(quote.targetPriceKrw)} hint="목표 마진 반영" /><Metric icon={<Layers3 />} label="활성 버전" value="V1.2" hint="승인 대기" /></div><div className="action-grid"><Action icon={<Box />} title="3D 형태 수정" text="기본형·부위 구성·삼면도 기준을 조정합니다." button="디자인 열기" click={() => setTab("design")} /><Action icon={<ClipboardCheck />} title="제조 사양 확정" text="BOM, 치수, 소재와 허용오차를 관리합니다." button="사양 열기" click={() => setTab("spec")} /><Action icon={<Calculator />} title="원가 시뮬레이션" text="MOQ·환율·난이도 변수를 즉시 반영합니다." button="견적 열기" click={() => setTab("quote")} /></div></article><aside className="approval-card"><p className="eyebrow">APPROVAL GATE</p><h2>다음 승인</h2><strong>V1.2 사양 동결 전</strong><p>부위별 치수와 원단 스펙을 확정한 뒤 공장 견적 요청을 보낼 수 있습니다.</p><button className="primary-button" onClick={() => setTab("spec")}>사양 점검하기 <ChevronRight size={16} /></button><div className="activity"><span>RECENT ACTIVITY</span><p><i /> 디자인 버전 V1.2 생성 <time>오늘</time></p><p><i /> 원가 시나리오 업데이트 <time>오늘</time></p><p><i /> QA 체크리스트 준비 <time>대기</time></p></div></aside></section>;
  };
  return <div className="studio-app"><aside className={`studio-sidebar ${menu ? "open" : ""}`}><div className="brand"><div><Sparkles size={17} /></div><section><b>PLUSH STUDIO</b><span>design to production</span></section><button className="close-menu" onClick={() => setMenu(false)}><X size={19} /></button></div><p className="workspace-label">WORKSPACE</p><button className="workspace">MOLIPOP Studio <ChevronRight size={15} /></button><nav>{tabItems.map(([id, label, Icon]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => { setTab(id); setMenu(false); }}><Icon size={18} /><span>{label}</span></button>)}</nav><footer><p><UsersRound size={16} /> 프로젝트 멤버 4</p><p><ShieldCheck size={16} /> Supabase RLS 보호</p></footer></aside>{menu && <button className="scrim" onClick={() => setMenu(false)} aria-label="메뉴 닫기" />}<main className="studio-main"><header className="topbar"><button className="menu-button" onClick={() => setMenu(true)}><Menu size={21} /></button><div className="crumbs">프로젝트 <ChevronRight size={15} /><b>{design.name}</b></div><div className="top-actions"><Pill accent>V1.2 · 내부 검토</Pill><button className="quiet-button" onClick={saveCloud}><Save size={16} /> 저장</button><button className="account-button" onClick={() => setLogin(true)}><Cloud size={16} /> {supabaseReady ? "클라우드 연결" : "연결 필요"}</button></div></header><header className="hero"><div><p className="eyebrow">PLUSH MANUFACTURING WORKFLOW</p><h1>{design.name}</h1><p>3D 형태, 제조 사양, 원가와 품질 승인 이력을 하나의 버전으로 연결합니다.</p></div><div><span>브랜드 <b>MOLIPOP</b></span><span>목표 출시 <b>2026. Q4</b></span><span>기준 수량 <b>{cost.quantity.toLocaleString()} pcs</b></span></div></header><div className="stage"><span className="done"><CheckCircle2 size={15} /> 초안</span><span className="done"><CheckCircle2 size={15} /> 내부 검토</span><span>3 공장 견적</span><span>4 샘플 검토</span><span>5 발주 확정</span><span>6 양산 QA</span></div><div className="content">{page()}</div><footer className="notice"><Cloud size={15} /> {note}<button onClick={() => setLogin(true)}>연결 정보</button></footer></main>{login && <div className="login-layer"><section className="login-card"><button onClick={() => setLogin(false)}><X size={19} /></button><div className="brand-mark"><Cloud size={19} /></div><p className="eyebrow">SECURE WORKSPACE</p><h2>프로젝트를 클라우드에 저장하세요.</h2><p>로그인 후 디자인 버전, GLB, Tech Pack, 견적과 QA 이력을 역할별로 관리합니다.</p><Field label="업무 이메일"><input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="name@company.com" /></Field><button className="primary-button full" onClick={signIn}><Send size={16} /> 로그인 링크 받기</button><small>공개 키에는 RLS가 적용되며 관리자 키는 브라우저에 노출되지 않습니다.</small></section></div>}</div>;
}

function Range({ label, value, unit, min, max, step, onChange }: { label: string; value: number; unit: string; min: number; max: number; step: number; onChange: (value: number) => void }) { return <label className="range"><span>{label}<b>{unit === "x" ? value.toFixed(2) : value} {unit}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={e => onChange(Number(e.target.value))} /></label>; }
function NumberInput({ value, onChange }: { value: number; onChange: (value: number) => void }) { return <div className="number-input"><input type="number" value={value} onChange={e => onChange(Number(e.target.value))} /><small>mm</small></div>; }
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="feature"><div>{icon}</div><strong>{title}</strong><p>{text}</p></article>; }
function Metric({ icon, label, value, hint }: { icon: React.ReactNode; label: string; value: string; hint: string }) { return <article className="metric"><div>{icon}</div><span>{label}</span><b>{value}</b><small>{hint}</small></article>; }
function Action({ icon, title, text, button, click }: { icon: React.ReactNode; title: string; text: string; button: string; click: () => void }) { return <article className="action"><div>{icon}</div><h3>{title}</h3><p>{text}</p><button onClick={click}>{button} <ArrowUpRight size={15} /></button></article>; }
